# Generated by Django 4.0 on 2022-02-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'permissions': (('pode_manipular_aluno', 'Manipula o cadastro de alunos.'),)},
        ),
    ]
